### PR TITLE
Fix SumN overflow.

### PR DESCRIPTION
**Pull request by syamajala**
Handle some overflow cases.

### CODE REVIEW

**Comment by vespos** [comment]
Looks good to me. 
I assume that any scalar data is already in int32 or float64 anyway?

**Comment by syamajala** [comment]
Not sure. @ddamiani or @chrisvam would probably know if we need to handle scalars as well?

**Comment by chrisvam** [comment]
Yes, I think scalars should be 32 or 64 bit (or float) so if it makes it easier we can ignore that case.

**Comment by vespos** [comment]
Closes #114

**Pull request merged**
